title: "[3D Slicer segmentation recipes](https://lassoan.github.io/SlicerSegmentationRecipes/)"
description: Recipes for common medical image segmentation tasks using 3D Slicer
theme: jekyll-theme-slate
